cmd_/home/jwilliams/mt7610u-linksys-ae6000-wifi-fixes/os/linux/../../rate_ctrl/alg_ags.o := gcc -Wp,-MD,/home/jwilliams/mt7610u-linksys-ae6000-wifi-fixes/os/linux/../../rate_ctrl/.alg_ags.o.d  -nostdinc -isystem /usr/lib/gcc/x86_64-linux-gnu/5/include  -I./arch/x86/include -Iarch/x86/include/generated/uapi -Iarch/x86/include/generated  -Iinclude -I./arch/x86/include/uapi -Iarch/x86/include/generated/uapi -I./include/uapi -Iinclude/generated/uapi -include ./include/linux/kconfig.h -Iubuntu/include  -D__KERNEL__ -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -m64 -falign-jumps=1 -falign-loops=1 -mno-80387 -mno-fp-ret-in-387 -mskip-rax-setup -mtune=generic -mno-red-zone -mcmodel=kernel -funit-at-a-time -maccumulate-outgoing-args -DCONFIG_X86_X32_ABI -DCONFIG_AS_FXSAVEQ=1 -DCONFIG_AS_SSSE3=1 -DCONFIG_AS_CRC32=1 -DCONFIG_AS_AVX=1 -DCONFIG_AS_AVX2=1 -pipe -Wno-sign-compare -fno-asynchronous-unwind-tables -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -fno-delete-null-pointer-checks -O2 --param=allow-store-data-races=0 -Wframe-larger-than=1024 -fstack-protector-strong -Wno-unused-but-set-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-var-tracking-assignments -pg -mfentry -DCC_USING_FENTRY -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -DCC_HAVE_ASM_GOTO -DSTA_DRIVER_BUILD="\"20141022-1327\"" -g -DAGGREGATION_SUPPORT -DPIGGYBACK_SUPPORT -DWMM_SUPPORT -DLINUX -Wall -Wstrict-prototypes -Wno-trigraphs -DSYSTEM_LOG_SUPPORT -DRT28xx_MODE=STA -DCHIPSET=mt7610u -DRESOURCE_PRE_ALLOC -DENHANCED_STAT_DISPLAY -I/home/jwilliams/mt7610u-linksys-ae6000-wifi-fixes/include -DDOT11_VHT_AC -DCONFIG_STA_SUPPORT -DSCAN_SUPPORT -DDBG -DWPA_SUPPLICANT_SUPPORT -DNATIVE_WPA_SUPPLICANT_SUPPORT -DDOT11_N_SUPPORT -DDOT11N_DRAFT3 -DNEW_RATE_ADAPT_SUPPORT -DSTATS_COUNT_SUPPORT -DRT_CFG80211_SUPPORT -DEXT_BUILD_CHANNEL_LIST -DLED_CONTROL_SUPPORT -DRTMP_TEMPERATURE_TX_ALC -DMT76x0 -DRT65xx -DRLT_MAC -DRLT_RF -DRTMP_MAC_USB -DRTMP_USB_SUPPORT -DRTMP_TIMER_TASK_SUPPORT -DA_BAND_SUPPORT -DRTMP_EFUSE_SUPPORT -DNEW_MBSSID_MODE -DCONFIG_ANDES_SUPPORT -DMT7610  -DMODULE  -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(alg_ags)"  -D"KBUILD_MODNAME=KBUILD_STR(mt7610u_sta)" -c -o /home/jwilliams/mt7610u-linksys-ae6000-wifi-fixes/os/linux/../../rate_ctrl/.tmp_alg_ags.o /home/jwilliams/mt7610u-linksys-ae6000-wifi-fixes/os/linux/../../rate_ctrl/alg_ags.c

source_/home/jwilliams/mt7610u-linksys-ae6000-wifi-fixes/os/linux/../../rate_ctrl/alg_ags.o := /home/jwilliams/mt7610u-linksys-ae6000-wifi-fixes/os/linux/../../rate_ctrl/alg_ags.c

deps_/home/jwilliams/mt7610u-linksys-ae6000-wifi-fixes/os/linux/../../rate_ctrl/alg_ags.o := \
    $(wildcard include/config/sta/support.h) \

/home/jwilliams/mt7610u-linksys-ae6000-wifi-fixes/os/linux/../../rate_ctrl/alg_ags.o: $(deps_/home/jwilliams/mt7610u-linksys-ae6000-wifi-fixes/os/linux/../../rate_ctrl/alg_ags.o)

$(deps_/home/jwilliams/mt7610u-linksys-ae6000-wifi-fixes/os/linux/../../rate_ctrl/alg_ags.o):
